version: '3.3'
services:
  web:
    container_name: flapjack_front
    build: ./
    ports:
      - '3000:3000' # expose ports - HOST:CONTAINER
    environment:
      - NODE_ENV=development
    env_file:
      - .env.dev
    volumes:
      - './:/usr/src/app'
      - '/usr/src/app/node_modules'
    stdin_open: true
